### ISSUE TITLE
Bug, bad behavior of the write_xyz operator

### ISSUE THREAD

**Issue by rprat-pro** [Collab4exaNBody/exaNBody#63]
This operator doesn't write files if the file name contains subdirectories.

Example: 

```
dump_data_xyz:
#  - timestep_file: "ExaDEMOutputDir/ExaDEMAnalyses/xyz_datas/dem_%09d.xyz"
  - timestep_file: "dem_%09d.xyz"
  - write_xyz_generic:
      fields: [ velocity, radius ]
      units: { velocity: "m/s", radius: "m" }

iteration_dump_writer:
  - dump_data_xyz

global:
  simulation_dump_frequency: 5000
```

This works with "dem_%09d.xyz", but nothing is done with "ExaDEMOutputDir/ExaDEMAnalyses/xyz_datas/dem_%09d.xyz".
