### ISSUE TITLE
lattice issue when size * repeats is not a multiple of cell_size 

### ISSUE THREAD

**Issue by rprat-pro** [Collab4exaNBody/exaNBody#67]
Replicate bug on exaDEM with spheres and a radius size of `0.5`

Bug: 

```
init:
  - lattice:
      structure: SC
      types: [ 0 ]
      size: [ 1.0 , 1.0 , 1.0 ]
      repeats: [ 5, 5 , 5 ]
domain:
  cell_size: 2.0 m
  periodic: [false,true,false]
```
 
It fails with repeats: `5`, `7`
It works with `4`, `6`, and `10`
It works if cell_size = `2.5`
It works if the periodic parameter it set to  [false,false,false]

It seems that the periodic boundary is not adapted to the size * repeats defined into the lattice operator, as the cell size is not adapted by the lattice operator. 

Solution: add a warning maybe ?
